language: android
android:
  components:
    - tools
    - android-8
    - build-tools-23.0.2

sudo: required

notifications:
  email: true
  irc: "irc.freenode.net#domogik"
  on_success: never
  on_failure: always

before_install:

  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

# Let's try to build...
script: ./gradlew clean build