language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-8
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - build-tools-22.0.1
  - android-22
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
script:
  - ./gradlew build --stacktrace
