language: android
jdk: oraclejdk8
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 25.1.x
    - platform-tools
    - build-tools-24.0.2
    - android-25


sudo: required

notifications:
  email: true
  irc: "irc.freenode.net#domogik"
  on_success: never
  on_failure: never

before_install:

  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

  - android update sdk --no-ui --filter build-tools-24.0.2,android-24,extra-android-m2repository
# Let's try to build...
script:
- android list target
- ./gradlew test
- ./gradlew clean
